### ISSUE TITLE
`replicate upload` command?

### ISSUE THREAD

**Issue by chigozienri** [replicate/cli#24]
It would be nice to provide access to the UploadFile function from the CLI

**Comment by mattt** [comment]
@chigozienri File uploads aren't an official part of Replicate's API yet. We have an experimental endpoint that we built for DreamBooth, and the CLI uses that as a convenience. So we should probably hold off on doing more here until we have a supported solution.

**Comment by anotherjesse** [comment]
🐼 😢 

@mattt I suspect the reason for not using the experimental dreambooth endpoint for prediction create is due to the upload endpoint not supporting all mimetypes?

but it is really :sad panda: we end up with base64 encoded for prediction create

**Comment by mattt** [comment]
#69 (nice) updates the CLI to use the files API for uploading files for prediction and training inputs. That API is intended to be mostly transparent, so we don't currently support file management subcommands.
