### ISSUE TITLE
`replicate train` requires inputs to be zip files

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cli#3]
Training Llama 13B fails with the following error:

```
replicate train a16z-infra/llama-2-13b-chat train_data="@/Users/andreas/Downloads/massive_abcnotation_dataset.pruned.jsonl" --destination=andreasjansson/abc-llama

Error: failed to parse inputs: failed to upload file: file is not a zip file
Usage:
  replicate train <owner/model[:version]> [input=value] ... [flags]

Flags:
  -d, --destination string   Destination model for training
  -h, --help                 help for train
      --json                 Emit JSON
  -s, --separator string     Separator between input key and value (default "=")
      --web                  View on web
```

**Comment by mattt** [comment]
@andreasjansson This is a limitation of our experimental DreamBooth API for file uploads, which supports only Zip files. To work around this, you can pass a URL to a different file type.

**Comment by mattt** [comment]
@andreasjansson Follow up on this — I was wrong! You can now upload any supported files as of [v0.2.2](https://github.com/replicate/cli/releases/tag/v0.2.2).

...though until [this PR is merged](https://github.com/replicate/replicate-web/pull/4836), `.jsonl` isn't a supported file format.
