### ISSUE TITLE
CLI deployments subcommand

### ISSUE THREAD

**Issue by jlewi** [replicate/cli#93]
It would be nice to have a CLI subcommand for the CRUD operations associated with deployments.
This would make be useful for CICD.
https://replicate.com/docs/reference/http#deployments.update

**Comment by mattt** [comment]
@jlewi Great idea! I pushed a draft PR with most of that here: https://github.com/replicate/cli/pull/95

Still need to implement `update` and `delete`, but `list`, `show`, `schema`, and `create` are working.
